### ISSUE TITLE
simpleterm creation

### ISSUE THREAD

**Issue by iham** [collective/collective.roster#10]
https://github.com/collective/collective.roster/blob/master/src/collective/roster/behaviors/groups.py#L82

why is the token derived from group (which is a tuple ) instead of normalizing the title or the id?

i use "id_from_normalized_groupname | groupname" for the roster groups.

on testing the value of the checkboxes are value="normalized_groupname-normalized_groupname" which is redundant... and somewhat hard to test...

wouldn't it be nicer to just normalize the title (the second part of the group tuple) for the token or use the plain id (first part of tuple)?

i wouldn't mind, spending that time, if there are no problems i don't see.

regards, iham

**Comment by datakurre** [comment]
For no good reason, I believe.

I suspect its just an artifact from the very first versions where groups were define by just titles and there was no support for | separator. When I added | separator, I did not update token formula.

Probably normalized version of "value" would work fine.

**Comment by iham** [comment]
i am fine with "value" too and will implement it that way.

done.

@datakurre can you publish it on pypi?

**Comment by datakurre** [comment]
Thanks. I should be able to do release on Monday.

**Comment by datakurre** [comment]
@iham Released 2.2.1. Took some time to fix issues on test setup.
