### ISSUE TITLE
short number not valid

### ISSUE THREAD

**Issue by svx** [collective/collective.roster#2]
If I try to set a short number [telephone] I get a not valid message.

3 letters short numbers a quite common in European offices :)  

![c_r-shortnr](https://cloud.githubusercontent.com/assets/358860/7699212/9dbdae00-fe16-11e4-8ffb-142059b3cf69.png)

**Comment by datakurre** [comment]
Fixing that validator to be more liberal should not harm too many:

https://github.com/collective/collective.roster/commit/b5514733be98b04149df750746af4812cd4402c3#diff-4b49984508659d9cae52f397c8ec803fR35

Feel free to fix. When it becomes an issue, it can be made p.registry configurable.
