### ISSUE TITLE
Plone 5.0.6 don't see roster in navigation(main menu) or default view for folder.

### ISSUE THREAD

**Issue by blu36iant** [collective/collective.roster#7]
I've to installed the add-on. It works i can create persons, groups and so on..
But the problem comes when i try to put the content accesible. If create a roster on the root of the site it doesn't appear in the main menu, if put it inside a folder i can't select it as a default view for that folder. Maybe i'm doing something wrong or i need to add some behavior to the roster content type to deal with that issue.

**Comment by datakurre** [comment]
I believe that these are all features in Plone. It's configurable, which types are shown in navigation and which types can be use as default page. See navigation, search and content options in the site setup.

**Comment by blu36iant** [comment]
Thanks!. Many times the solution is simpler than one thinks.
